import { Inter } from "next/font/google";
import Script from "next/script";
import "./example.css";
import "./bootstrap.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blueprint 3D - Example",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <Script src="./three.min.js"></Script>
      <Script src="./blueprint3d.js"></Script>
      <Script src="./jquery.js"></Script>
      <Script src="./items.js"></Script>
      {/* <Script src="./bootstrap.js"></Script> */}
      <Script src="./example.js"></Script>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
